### ISSUE TITLE
Initial Docs

### ISSUE THREAD

**Issue by aeplay** [garden-co/classic-jazz#188]

**Comment by trishalim** [comment]
Can we use this ticket for restructuring the docs as suggested by Tobias?

His suggestion:

1. Getting Started

1.1 Installation

1.2 Quickstart Guide (minimal setup, not linear!)

1.3 Advanced Guide (Linear) - maybe somewhere else?

2. Building your Application

2.1 Schema (how to define a jazz schema)

2.2 CoMaps & Lists

2.3 Images & Binary Data

2.3 Ref CoValues

2.4 Node.js

3. API Reference (which is currently autogenerated) - this currently adds quite some bloat - [Next.js API Ref](https://nextjs.org/docs/app/api-reference)

**Comment by trishalim** [comment]
<img src="https://uploads.linear.app/acccaaae-2ae4-487e-a83c-7148ce16c659/e92f801c-e8b1-429d-aa1e-60e36d02711e/659a275b-fe4b-4260-baf8-0fb9b81a2ba1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FjY2NhYWFlLTJhZTQtNDg3ZS1hODNjLTcxNDhjZTE2YzY1OS9lOTJmODAxYy1lOGIxLTQyOWQtYWExZS02MGUzNmQwMjcxMWUvNjU5YTI3NWItZmU0Yi00MjYwLWJhZjgtMGZiOWI4MWEyYmExIiwiaWF0IjoxNzI4NDkzMDAxLCJleHAiOjMzMjk5MDUzMDAxfQ.dJTqyUaTlRFCnnPZNk6jhTEYvqQzgnACPzf6cb6OcPI " alt="image.png" width="999" height="293" />
