### ISSUE TITLE
WebSocket connection to 'wss://sync.jazz.tools/' failed

### ISSUE THREAD

**Issue by rozek** [garden-co/classic-jazz#190]
Hi!

I just wanted to have a look at jazz and tried the referenced example `https://example-todo.jazz.tools` but could not even open a connection to your servers (as shown by the error log found in my browser's console):

```
 WebSocket connection to 'wss://sync.jazz.tools/' failed: 
createWebSocketPeer	@	/assets/index-97472e40.js:16765
 Error reading from peer wss://sync.jazz.tools@2024-05-22T03:39:40.106Z Error: The WebSocket errored!
    at WebSocket.<anonymous> (/assets/index-97472e40.js:16755:30)
readIncoming	@	/assets/index-97472e40.js:15193
```

Trying to `open('https://sync.jazz.tools/')` revealed that the server is principally working, but the websocket connection failed.

Any ideas how to proceed?

Thanks in advance for any help!

**Comment by rozek** [comment]
What _did_ work, however, was your chat example in [the docs](https://jazz.tools/)...

**Comment by aeplay** [comment]
If you open https://sync.jazz.tools/health in your browser, what do you get?

**Comment by rozek** [comment]
the response is `OK@newyor` and the browser console remains empty...

**Comment by aeplay** [comment]
That means you can connect fine over HTTP - any chance you are behind a firewall or something that messes with websockets?

**Comment by rozek** [comment]
no firewall, and other websocket servers outside my HomeLAN work fine. I'm not at home right now, but I could test again tomorrow morning

**Comment by rozek** [comment]
ok, I tried the exampel again - as promised.

Today, it seems to work: I can create a new account, a new project, work with tasks, invite somebody else and share tasks between all participants.

Perhaps, there was a temporary problem with the server last time...

Just FYI: there is a warning in my browser's console:

```
index-4ef9b752.js:32799 publicKey.pubKeyCredParams is missing at least one of the default algorithm identifiers: ES256 and RS256. This can result in registration failures on incompatible authenticators. See https://chromium.googlesource.com/chromium/src/+/main/content/browser/webauth/pub_key_cred_params.md for details
```

**Comment by aeplay** [comment]
Thanks for trying again, it most likely was something temporary. Will iron out some smaller reliability issues over the next days.

The error you mention is harmless but tracked in https://github.com/gardencmp/jazz/issues/151

**Comment by rozek** [comment]
Thanks for your effort!
