### ISSUE TITLE
Uncaught (in promise) Error: Pica: cannot use getImageData on canvas, make sure fingerprinting protection isn't enabled

### ISSUE THREAD

**Issue by rozek** [garden-co/classic-jazz#191]
Hi!

I just tried the example found at https://example-pets.jazz.tools/ and did not even succeed to run it locally - see the following error log from my browser:

```
Uncaught (in promise) Error: Pica: cannot use getImageData on canvas, make sure fingerprinting protection isn't enabled
```

Additionally, I also could not open a websocket connection to your server(s) (as described in my previous [issue](https://github.com/gardencmp/jazz/issues/190)).

Any idea how to proceed?

**Comment by aeplay** [comment]
Hi @rozek, thanks for trying! Which browser/OS are you using?

**Comment by rozek** [comment]
Hello,

thanks for your response!

I am using macOS Ventura 13.6 with the latest Brave Browser [Version 1.66.110 Chromium: 125.0.6422.60 (Offizieller Build) (arm64)](https://brave.com/latest/)

**Comment by aeplay** [comment]
Are you by chance using Brave's "Strict fingerprinting protection mode"?

**Comment by rozek** [comment]
Similar to the other issue I mentioned above, I tried the example again today - and it worked now.

Could it be that the error I reported was just a consequence of the missing websocket connection?

**Comment by aeplay** [comment]
I'd be surprised, because the image resizing is a completely local operation and should work/not work the same regardless of if you have a working connection to the sync server.

You didn't by chance update Brave in the meantime? (it sounded like they were working on exactly the fingerprinting strictness)

**Comment by rozek** [comment]
well, it _could_ be that I updated Brave (as that happens quite often) but I can't tell you for sure.

Anyway, thanks a lot for your effort!
