### ISSUE TITLE
Jazz React: performance issues on keypress

### ISSUE THREAD

**Issue by gdorsi** [garden-co/classic-jazz#201]
While playing with the tutorial I felt the input interactions a little laggy, so I've spinned the profiler and got this:

<img width="254" alt="Screenshot 2024-05-31 at 10 14 23" src="https://github.com/gardencmp/jazz/assets/6529568/4284c8d8-e78f-47a0-96ac-f57456b01c23">

I'm on a Macbook pro with an M2 processor and the recording is done without CPU throttling.

It looks like the main cost is related to the encryption part and the serailization to WASM:
<img width="567" alt="Screenshot 2024-05-31 at 10 15 02" src="https://github.com/gardencmp/jazz/assets/6529568/d9e8262c-ce00-42ec-ad05-f330bd8e7518">

**Comment by aeplay** [comment]
Hey @gdorsi can you please try again with `jazz-tools@0.7.10` and `jazz-react@0.7.10`?

I'm now caching the value that was redundantly re-derived (the AgentID).

Weirdly enough, I have similar specs to you and got <4ms per keystroke before, now it is <2ms
Would really appreciate if you could do another trance on the new version

**Comment by gdorsi** [comment]
Yep, problem solved!

<img width="406" alt="Screenshot 2024-06-26 at 09 58 08" src="https://github.com/gardencmp/jazz/assets/6529568/909f2517-60ee-4eba-aa37-4b2e5fd77f11">

Thanks!
