### ISSUE TITLE
New example of running a mesh server locally

### ISSUE THREAD

**Issue by mirshko** [garden-co/classic-jazz#217]
It looks like the `cojson-simple-sync` has been marked as old now. It would be great to have an example or even a docker image to spin up for providing a local mesh worker while developing!

**Comment by aeplay** [comment]
You can still use `npx cojson-simple-sync` - it uses the old version of core packages but is protocol-compatible.

Soon the local sync server will be part of the WIP jazz CLI (`jazz-run`)

**Comment by aeplay** [comment]
for tracking that: https://github.com/gardencmp/jazz/issues/219
