### ISSUE TITLE
Project changed  code is incorrectly highligted

### ISSUE THREAD

**Issue by danielo515** [garden-co/classic-jazz#353]
Hello.
I'm just having some fun with jazz, following the tutorial, and I noticed this in the docs (see screenshot):
<img width="937" alt="Screenshot 2024-08-28 at 08 16 46" src="https://github.com/user-attachments/assets/75babb3a-44de-4b2d-87ed-ab7159f9b9a3">

As you can see, only the `useState` line is highlighted, where in reality also the parsing of the url and the coerce need to change in order for the example to work.
 
Great library, keep up the good work.

**Comment by aeplay** [comment]
Hey, thanks for catching this and glad you're enjoying Jazz. Will close this once fixed.
