### ISSUE TITLE
Jazz repo root README guide for scripts

### ISSUE THREAD

**Issue by callumflack** [garden-co/classic-jazz#360]
Perhaps a note in the root's README about Turbo and what scripts to run first? (And then hope people read it…)

**Comment by trishalim** [comment]
<img src="https://uploads.linear.app/acccaaae-2ae4-487e-a83c-7148ce16c659/e3eb44ef-dc6c-470d-aa22-c9270eb18146/dd5faf03-57fd-448d-b782-488ac9f995e9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FjY2NhYWFlLTJhZTQtNDg3ZS1hODNjLTcxNDhjZTE2YzY1OS9lM2ViNDRlZi1kYzZjLTQ3MGQtYWEyMi1jOTI3MGViMTgxNDYvZGQ1ZmFmMDMtNTdmZC00NDhkLWI3ODItNDg4YWM5Zjk5NWU5IiwiaWF0IjoxNzMwODM4MzIzLCJleHAiOjMzMzAxMzk4MzIzfQ.nbKI3meExPPU8-AqultFU8JLKD03gZ60HrFDeQpTk58 " alt="image.png" width="721" height="72" />
