### ISSUE TITLE
Improve how the WIP banners and links to Github in the docs look

### ISSUE THREAD

**Issue by aeplay** [garden-co/classic-jazz#400]
<img src="https://uploads.linear.app/acccaaae-2ae4-487e-a83c-7148ce16c659/07f82deb-c6a3-4f9a-9692-694cfb81a2a3/783f60be-eeae-4999-8073-f7e7cac57fef?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FjY2NhYWFlLTJhZTQtNDg3ZS1hODNjLTcxNDhjZTE2YzY1OS8wN2Y4MmRlYi1jNmEzLTRmOWEtOTY5Mi02OTRjZmI4MWEyYTMvNzgzZjYwYmUtZWVhZS00OTk5LTgwNzMtZjdlN2NhYzU3ZmVmIiwiaWF0IjoxNzI2NTk0NTU4LCJleHAiOjMzMjk3MTU0NTU4fQ.rGBlzKVjHojchBiS66L4pUnVTgbs6lz3UPcXQ7gH7cY " alt="image.png" width="521" height="42" />

**Comment by trishalim** [comment]
I realized why I don't like how this looks. It doesn't look great by itself:

<img src="https://uploads.linear.app/acccaaae-2ae4-487e-a83c-7148ce16c659/f99fd7d2-32d5-455a-b087-31e9f38c693e/9026258f-be19-41c3-9fbb-c692705657bd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FjY2NhYWFlLTJhZTQtNDg3ZS1hODNjLTcxNDhjZTE2YzY1OS9mOTlmZDdkMi0zMmQ1LTQ1NWEtYjA4Ny0zMWU5ZjM4YzY5M2UvOTAyNjI1OGYtYmUxOS00MWMzLTlmYmItYzY5MjcwNTY1N2JkIiwiaWF0IjoxNzI2NTk0ODgwLCJleHAiOjMzMjk3MTU0ODgwfQ.ZdSTDZuDLJj3kYQJixLUSV0TH9r6tpq09gYSXV38_8k " alt="image.png" width="521" height="42" />

Fixing that only makes it a tiny bit better.

The real problem are these empty sections grouped together:

<img src="https://uploads.linear.app/acccaaae-2ae4-487e-a83c-7148ce16c659/353ebba6-5211-4d91-b789-30de334c6e68/e5a11746-3958-4e0c-ab24-29a05271f266?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FjY2NhYWFlLTJhZTQtNDg3ZS1hODNjLTcxNDhjZTE2YzY1OS8zNTNlYmJhNi01MjExLTRkOTEtYjc4OS0zMGRlMzM0YzZlNjgvZTVhMTE3NDYtMzk1OC00ZTBjLWFiMjQtMjlhMDUyNzFmMjY2IiwiaWF0IjoxNzI2NTk0ODgwLCJleHAiOjMzMjk3MTU0ODgwfQ.HPAgArLnZrzfKSbFR06hQie-1_BJ9KV6Nz1J9-7Bs9U " alt="image.png" width="1246" height="680" />

And this whole page feels never-ending. I find myself getting lost, then trying to get back to where I was by clicking on the sidebar.

The solution isn't to redesign the "OH NO" alert, but to create different pages for each section from the nav.

<img src="https://uploads.linear.app/acccaaae-2ae4-487e-a83c-7148ce16c659/00a0fd21-5423-47e6-ab9e-1b68941e6697/9a3b051c-0670-449f-bac0-f6c3cea789c4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FjY2NhYWFlLTJhZTQtNDg3ZS1hODNjLTcxNDhjZTE2YzY1OS8wMGEwZmQyMS01NDIzLTQ3ZTYtYWI5ZS0xYjY4OTQxZTY2OTcvOWEzYjA1MWMtMDY3MC00NDlmLWJhYzAtZjZjM2NlYTc4OWM0IiwiaWF0IjoxNzI2NTk0ODgwLCJleHAiOjMzMjk3MTU0ODgwfQ.oqIeeUYQYGfvdHBpKHpRHKJ57JtH9H3M0eDT2OhUkt8 " alt="image.png" width="1263" height="589" />

@anselm What do you think?

**Comment by aeplay** [comment]
Makes sense! Thanks for challenging this. Happy to close this ticket, feel free to create one for splitting things into more pages and start to work on that.

**Comment by anselm** [comment]
Looks like a cool project!
