### ISSUE TITLE
Improve styling for code snippets

### ISSUE THREAD

**Issue by trishalim** [garden-co/classic-jazz#421]
Problems

- [X] Too much left padding
- [ ] Faded text is not readable. We can highlight the new lines instead of fading out the old ones.
- [X] Font size too small
- [ ] ~~Horizontal scrolling. Wrap the text.~~
- [ ] ~~Add max height?~~

Here's a comparison with Tailwind and Radix UI

![image.png](https://uploads.linear.app/acccaaae-2ae4-487e-a83c-7148ce16c659/91d319cf-1a3c-4e98-8311-99efd7a61788/43cd4bef-895b-4a4b-9e4b-29036b224e21?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FjY2NhYWFlLTJhZTQtNDg3ZS1hODNjLTcxNDhjZTE2YzY1OS85MWQzMTljZi0xYTNjLTRlOTgtODMxMS05OWVmZDdhNjE3ODgvNDNjZDRiZWYtODk1Yi00YTRiLTllNGItMjkwMzZiMjI0ZTIxIiwiaWF0IjoxNzI2NzcxNjY4LCJleHAiOjMzMjk3MzMxNjY4fQ.Ft9Cm6gLDKb1XXVy2-vkMPeN-w6x4oXCOwLO7BTS3uM "=1984x")

**Comment by aeplay** [comment]
Agree with everything except let's keep horizontal scrolling and manually try to prevent long lines in the snippets as we create them
