### ISSUE TITLE
Redesign side nav

### ISSUE THREAD

**Issue by trishalim** [garden-co/classic-jazz#423]
Remove prose, it's more for articles / markdown content

It's easy to get lost when browsing the api references. [Highcharts](https://api.highcharts.com/highcharts/navigation.bindings.ellipseAnnotation) handles this by highlighting

<img src="https://uploads.linear.app/acccaaae-2ae4-487e-a83c-7148ce16c659/52961b6f-f63e-42ba-aa8b-59cd225f7c89/4d1298c1-7f61-44cc-9cf7-ea20a16a79f2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FjY2NhYWFlLTJhZTQtNDg3ZS1hODNjLTcxNDhjZTE2YzY1OS81Mjk2MWI2Zi1mNjNlLTQyYmEtYWE4Yi01OWNkMjI1ZjdjODkvNGQxMjk4YzEtN2Y2MS00NGNjLTljZjctZWEyMGExNmE3OWYyIiwiaWF0IjoxNzI2Nzc4NDMwLCJleHAiOjMzMjk3MzM4NDMwfQ.z66uUoVLh8NzAB8l1GufbuPDqzXlZpBrLyar6dEpZ3g " alt="image.png" width="1328" />

Maybe separate page for every item, not every package?

[Ghost](https://ghost.org/docs/ghost-cli/#ghost-restart) adds a nav to the right. This is cleaner but we'll need to make the container wider. I like this one better.

<img src="https://uploads.linear.app/acccaaae-2ae4-487e-a83c-7148ce16c659/b6104e7c-c529-42dd-b2ea-be1e0c2bad21/c38226d5-5945-4ed2-b5b8-60105f32d6b5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FjY2NhYWFlLTJhZTQtNDg3ZS1hODNjLTcxNDhjZTE2YzY1OS9iNjEwNGU3Yy1jNTI5LTQyZGQtYjJlYS1iZTFlMGMyYmFkMjEvYzM4MjI2ZDUtNTk0NS00ZWQyLWI1YjgtNjAxMDVmMzJkNmI1IiwiaWF0IjoxNzI2Nzc4NDMwLCJleHAiOjMzMjk3MzM4NDMwfQ.hnyKDiLSV56Tb3wIF3eYbSD-7db_Rh1SkUMOccmvY1w " alt="image.png" width="1436" />

**Comment by tobiaslins** [comment]
I'll just put my thoughts on this topic.

1. Getting Started
1.1 Installation
1.2 Quickstart Guide (minimal setup, not linear!)
1.3 Advanced Guide (Linear) - maybe somewhere else?
2. Building your Application
2.1 Schema (how to define a jazz schema)
2.2 CoMaps & Lists
2.3 Images & Binary Data
2.3 Ref CoValues
2.4 Node.js 
3. API Reference (which is currently autogenerated) - this currently adds quite some bloat - [Next.js API Ref](https://nextjs.org/docs/app/api-reference)


Thoughts? :)

**Comment by trishalim** [comment]
@tobiaslins Thanks for writing this up! I definitely agree that we need individual sections, and have the tutorial separate.

Re the bloat in API Reference, are you saying it's loading slow for you? The whole docs used to be one big page, but now each package is its own page.
