### ISSUE TITLE
Add og image and description for social sharing

### ISSUE THREAD

**Issue by trishalim** [garden-co/classic-jazz#475]
<img src="https://uploads.linear.app/acccaaae-2ae4-487e-a83c-7148ce16c659/d9c4c774-1c75-4645-ad9b-ed6cd3250a17/5ac54b35-8634-4b62-a0e0-367316265e28?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FjY2NhYWFlLTJhZTQtNDg3ZS1hODNjLTcxNDhjZTE2YzY1OS9kOWM0Yzc3NC0xYzc1LTQ2NDUtYWQ5Yi1lZDZjZDMyNTBhMTcvNWFjNTRiMzUtODYzNC00YjYyLWEwZTAtMzY3MzE2MjY1ZTI4IiwiaWF0IjoxNzI3ODgzNzQzLCJleHAiOjMzMjk4NDQzNzQzfQ.OsQuYJIu7qqlVN5mbKTj8pNu53h3UWTISaLpFnPJZOE " alt="image.png" width="351" height="142" />

**Comment by aeplay** [comment]
We can use Vercel's OG preview feature to debug those:

https://vercel.com/gcmp/jazz-homepage/5BXA8kt5NDENpZRfcojg9Y3nd9Z7/og

(you can find them on each deployment)
