### ISSUE TITLE
Add social proof

### ISSUE THREAD

**Issue by trishalim** [garden-co/classic-jazz#506]
Social proof can go into the homepage or showcase page

**Comment by trishalim** [comment]
@aeplay Assigning to you so you can gather the social proof, then I will add them to the site.

**Comment by aeplay** [comment]
"Our friend started his startup at the same time as we started Invoice Radar.
He was using Supabase, we were using Jazz.
When he finished configuring everything, we had an MVP."

-- creators of Invoice Radar

----

"Hey guys! Got most of [important app feature] working yesterday (in the web version). Really happy with Jazz so far. DX is very nice. And offline works exactly how I'd like. I actually got all of this working while on the plane without wifi 🤯"

-- CTO of stealth startup

----

TODO: quote from Nikita

**Comment by trishalim** [comment]
We already have some testimonials. We can gather some more when needed
