### ISSUE TITLE
Rename Jazz Mesh to Jazz Cloud

### ISSUE THREAD

**Issue by trishalim** [garden-co/classic-jazz#545]

**Comment by trishalim** [comment]
@aeplay I removed myself so @bensleveritt can take it if he wants?

**Comment by bensleveritt** [comment]
Are we renaming the mesh subdomain at this point @aeplay? (`wss://mesh.jazz.tools` -> `wss://cloud.jazz.tools`)

**Comment by aeplay** [comment]
Yes! I'll make sure there is a DNS alias set up before we merge this PR

**Comment by bensleveritt** [comment]
And is the name Jazz Cloud (instead of Jazz Global Mesh)?

**Comment by aeplay** [comment]
Yes
