### ISSUE TITLE
Define docs outline

### ISSUE THREAD

**Issue by trishalim** [garden-co/classic-jazz#550]
1. Introduction
   1. What is Jazz?
   2. Supported environments
   3. Where to start?
      1. Link to Guide
      2. Link to examples
      3. Link to project setup
   4. Jazz mesh
2. Project setup/Installation
   1. React (copy this but create a react app instead of `npx degit gardencmp/vite-ts-react-tailwind`)
   2. React Native
3. Schema
   1. CoValues/Introduction to CoValues (What are covalues)
   2. Defining
      1. CoMap
         1. different types you can use like string number, date, a reference to another covalue
      2. CoList
   3. Creating
   4. Reading & Subscribing
      1. Loading depth
   5. Updating
   6. Deleting
4. Auth
   1. Setting up 
      1. Clerk
      2. DemoAuth?
   2. Account
      1. Profile
      2. Root
      3. Creating initial data (search `extends Account` in jazz repo)

**Comment by trishalim** [comment]
@[bensleveritt](https://github.com/gardencmp/jazz/issues?q=is%3Aissue+is%3Aopen+author%3Abensleveritt) @aeplay Is this good to start with?

**Comment by aeplay** [comment]
This looks roughly OK, thank you for collecting it - how about you make a PR where you build this structure as docs nav (ignore looks and content not existing for now) and then we can make precise suggestions on that PR?
