### ISSUE TITLE
Create Next.JS "use-client"-only example app

### ISSUE THREAD

**Issue by aeplay** [garden-co/classic-jazz#554]

**Comment by aeplay** [comment]
@trishalim I guess the book-shelf is like this?

**Comment by trishalim** [comment]
@aeplay yes, to quote you: "you should be able to use create-next-app and then make sure you put the jazz context in a client component and all components that use jazz hooks are also client components"

**Comment by aeplay** [comment]
Perfect, we will document this in [https://github.com/gardencmp/jazz/issues/552](https://github.com/gardencmp/jazz/issues/552)
