### ISSUE TITLE
Redesign nav

### ISSUE THREAD

**Issue by trishalim** [garden-co/classic-jazz#648]
![image.png](https://uploads.linear.app/acccaaae-2ae4-487e-a83c-7148ce16c659/6fbf9844-57d2-4dce-a6a9-04579904d116/6c4bc137-4b8d-4c6b-8b93-99ec5c888b47?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FjY2NhYWFlLTJhZTQtNDg3ZS1hODNjLTcxNDhjZTE2YzY1OS82ZmJmOTg0NC01N2QyLTRkY2UtYTZhOS0wNDU3OTkwNGQxMTYvNmM0YmMxMzctNGI4ZC00YzZiLThiOTMtOTllYzVjODg4YjQ3IiwiaWF0IjoxNzMwNDUzMDI0LCJleHAiOjMzMzAxMDEzMDI0fQ.n9jWVqyKwlWNLNruArQye-zHkvs_6xm1ctWgyY2vUxI "=1303x")

- [X] Nav is too crowded. Maybe we can move Releases and Roadmap to footer
- [X] Missing CTA
- [X] Change Twitter icon to X
- [X] Remove hover effect on logo
- [X] Layout shifts a tiny bit when navigating because of the font-weight change on the active nav item
- [ ] There are 2 hamburger menus in mobile
- [ ] Redesign mobile nav (maybe in a separate issue though)

We can also do a mega menu for "Docs" nav item that lists the docs and the api reference. This way, the side nav inside docs is less crowded

**Comment by aeplay** [comment]
Yeah mobile nav deserves a separate issue. Agree on everything else
