### ISSUE TITLE
Close mobile nav after clicking a link

### ISSUE THREAD

**Issue by trishalim** [garden-co/classic-jazz#655]

**Comment by aeplay** [comment]
thanks for spotting this!

**Comment by trishalim** [comment]
@aeplay wasn't me :D 
<img width="476" alt="image" src="https://github.com/user-attachments/assets/314fa943-ca79-4e80-b6ea-47809e8259a1">

**Comment by aeplay** [comment]
🚨 intruder alert 🚨
