### ISSUE TITLE
Add minimal Clerk example

### ISSUE THREAD

**Issue by gdorsi** [garden-co/classic-jazz#806]

**Comment by trishalim** [comment]
Instead of adding a new example, it would be better to use the existing chat example and remove the chat stuff. Also, this is for React right?

**Comment by gdorsi** [comment]
Ok, so we can remove the `chat-clerk` app (agree since the only difference with the chat is the auth).

> Also, this is for React right?

Do you think we should make one also for VueJS?

**Comment by trishalim** [comment]
Yes that would be nice<br>Though I think we should finish doing this in React for all the different features to nail the DX, before moving on to Vue.
